#!/usr/bin/env perl

use 5.010;
use strict;
use utf8;
use warnings;

use File::Slurper qw(read_text);

binmode STDOUT, ":utf8";

my @w;
my %mem;

for my $file (<../devdata/*:*>) {
    my $ct = read_text($file);

    while ($ct =~ m!^<li><a href="/wiki[^>]+>(.+?)</a></li>!gm) {
        next if $mem{$1}++;
        push @w, $1;
    }
}

say for sort @w;
